-- MySQL Script generated by MySQL Workbench
-- Fri Oct 15 02:15:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sistema` (
  `idSistema` INT NOT NULL,
  `Interfaz` VARCHAR(45) NULL,
  PRIMARY KEY (`idSistema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trabajador` (
  `idTrabajador` INT NOT NULL,
  `Usuario` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(45) NULL,
  `Dni` VARCHAR(45) NULL,
  `Nombres` VARCHAR(45) NULL,
  `Celular` VARCHAR(45) NULL,
  `Portafolio` VARCHAR(45) NULL,
  `Profesion` VARCHAR(45) NULL,
  `Sistema_idSistema` INT NOT NULL,
  PRIMARY KEY (`idTrabajador`, `Sistema_idSistema`),
  INDEX `fk_Trabajador_Sistema1_idx` (`Sistema_idSistema` ASC) VISIBLE,
  CONSTRAINT `fk_Trabajador_Sistema1`
    FOREIGN KEY (`Sistema_idSistema`)
    REFERENCES `mydb`.`Sistema` (`idSistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Anuncio` (
  `idAnuncio` INT NOT NULL,
  `Valoracion` VARCHAR(45) NULL,
  `Sistema_idSistema` INT NOT NULL,
  PRIMARY KEY (`idAnuncio`),
  INDEX `fk_Anuncio_Sistema1_idx` (`Sistema_idSistema` ASC) VISIBLE,
  CONSTRAINT `fk_Anuncio_Sistema1`
    FOREIGN KEY (`Sistema_idSistema`)
    REFERENCES `mydb`.`Sistema` (`idSistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `idAdministrador` INT NOT NULL,
  `Usuario` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(45) NULL,
  `Rol` VARCHAR(45) NULL,
  `Sistema_idSistema` INT NOT NULL,
  PRIMARY KEY (`idAdministrador`, `Sistema_idSistema`),
  INDEX `fk_Administrador_Sistema1_idx` (`Sistema_idSistema` ASC) VISIBLE,
  CONSTRAINT `fk_Administrador_Sistema1`
    FOREIGN KEY (`Sistema_idSistema`)
    REFERENCES `mydb`.`Sistema` (`idSistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedores` (
  `idProveedores` INT NOT NULL,
  `Usuario` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(45) NULL,
  `RUC` VARCHAR(45) NULL,
  `NombredeEmpresa` VARCHAR(45) NULL,
  `Celular` VARCHAR(45) NULL,
  `TipodeProfesion` VARCHAR(45) NULL,
  `Sistema_idSistema` INT NOT NULL,
  PRIMARY KEY (`idProveedores`, `Sistema_idSistema`),
  INDEX `fk_Proveedores_Sistema_idx` (`Sistema_idSistema` ASC) VISIBLE,
  CONSTRAINT `fk_Proveedores_Sistema`
    FOREIGN KEY (`Sistema_idSistema`)
    REFERENCES `mydb`.`Sistema` (`idSistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
